### ISSUE TITLE
1.18.1

### ISSUE THREAD

**Issue by RatDonkeyGoat** [orlouge/amphitrite-coffer#4]
not sure if its supposed to work on this version but it does not

**Comment by orlouge** [comment]
It's built for 1.18.1. What does it mean it doesn't work? Is there an error somewhere? Post it please.

**Comment by RatDonkeyGoat** [comment]
everything loads fine you just cant open them lol no error

**Comment by orlouge** [comment]
They need to be waterlogged or charged, otherwise you can't open them, it's intentional.

**Comment by RatDonkeyGoat** [comment]
im an idiot im sorry :(
